language: node_js
node_js:
- '14'
sudo: false
branches:
  only:
  - master
before_script:
- npm install
- npm install codecov
script:
- npm run docs:gen
- npm run test
after_success:
- cd $TRAVIS_BUILD_DIR
- chmod +x generateDocs.sh
- bash generateDocs.sh
- codecov
env:
  global:
  - secure: eGafAystSQr0wW+jAIVdQ8i08oFn4S6jGDURZyJ/N/c6uAslIEMlIabgqJjkYknXnOY05B3DpAkvj7e9Y4jNXAsSg3OW8BuQugch+G/kGPRWudWjHl+HE6VGR9TsGwgLyyrwCafXgToYI4nG707fcGOi3NyPJCvOoVICUUfKE5G5fpnnLKAPGzdJ6+bLUB2QigyclB5Cn9SVXeTAh1CqF84DHilyd1I3k2yTWiKaU8oKN3LCwNFNsZWzbF8bfP0K4aXB2bq1E8yki8LGQ0ZC1gtaRSI+kOk55XXYJ5wW7vN3mqKsOx3XV/fRy8YHhsbM+zMuReYpaFx0s8uH1bkk+XdWAjwF79dQDTfvZvK3PHMlAvOSfTKVC1wg/PIo5EF3pRodWBpcJt8whkPS9JWD7PUzhsWhIPzyimJLwXpuAFYFrApPtev9nxIFmolbfeAC/ZWgWbsse5iWvMYGUAmlSMhv8cWjtvc64kvfQNvKmCIScsbiCr+8n4jv5yQ/uI08kElfytbK4esSUTR2GuQkSmrqIbsGDgX2TCLJGI+U+1dL75quQpzUNUyzRNAbXZ1suCXz3vD6InfTCMnEWyxfvoLN/dhXszeoewO2gFQFQLytzr6Oo9F0rgzYihymCyWVAiDdAQLC57x7ThlxIl7ZkRj44hpvLGwG5hVQL8peRs4=
  - secure: uvIn3m4eOFTgGjtga75YOD3gJPDRITfQPjYixEsbCdEM8Pfgl7AqwlD+i+fx9euFNnKb+EWe5Ynh4vekAjZP5KU+a9LkSjfBrMCYkkareZPtOLnNavm6dpWPwNSrfXa0yf+qhDTr0CEIeXSXy0G/1u/BXhwMbjSlovkvd0/BwebcPvZLLZSJeBUsJnf1a022WPa4U8VWTiUyYy+nibQuAEdSxi/UZ6YstNLnfSjGQvAJoFHqLe7syaN8gozNkHO3P4IXDPE008Wb1rLOHkC6pWdoF05l09YrZCUF5ZJzKc5Dvfpwdbf02epe6ORb21xHde3Pp4qYaEz6jvrqPCMJmuaTJXetXphnY17Qw6pYk/aXdwxWnEWeUm2qBJNejaI5ISvI+/Y3np1mVQ9dwuf28+ls+JtcZ6V61JG2c9cBeno4wFUVmtBg2HNDiIDhCkg207mrNcEiHHbJz7hj8MxskCVY8nYVs7rX9Y7A2cb909cPcKpXPc7AdHQufzMEpyjkAnY65NdBlprMwhkbS/i4T8XDIZPmw+QOGyACY7fNlOzVE4wLoyZ+mSQNN0s3PKTkF2vGJhe1IOk2+w5onxLqfyVFk4U6ZWVX6im4xuvD5dPXwrXhPHtNrmLDk2XHgIrUv9HleMI5nloHIYSGJxoa9v+ZdtKiNKqzL+IOu7D9M1M=
