export const GRAY_PUBLISH_OPERATION = {
  FIRST_GRAY_PUBLISH: 'FIRST_GRAY_PUBLISH',
  UPDATE_GRAY_PERCENT: 'UPDATE_GRAY_PERCENT',
  PUBLISH_ALL_GRAY: 'PUBLISH_ALL_GRAY',
  RECALL_ALL_GRAY: 'RECALL_ALL_GRAY',
};


export const GRAY_PUBLISH_TITLE_MAP = {
  [GRAY_PUBLISH_OPERATION.UPDATE_GRAY_PERCENT]: '更新灰度比例',
  [GRAY_PUBLISH_OPERATION.PUBLISH_ALL_GRAY]: '全量发布',
  [GRAY_PUBLISH_OPERATION.RECALL_ALL_GRAY]: '撤销灰度',
};
