export type IEnv = {
  isWeixin: boolean,
  isWorkWeixin: boolean,
  isQQ: boolean,
  isPvpApp: boolean,
  isTipApp: boolean,
  isAndroid: boolean,
  isIos: boolean,
  isIOS: boolean,
  isMsdk: boolean,
  isMsdkV5: boolean,
  isSlugSdk: boolean,
  isInGame: boolean,
  isGHelper: boolean,
  isGHelper20004: boolean,
  isMiniProgram: boolean,
  isLolApp: boolean,
  isWindowsPhone: boolean,
  isSymbian: boolean,
  isPc: boolean,
};
